// Code generated by "accessor -type=FieldModel"; DO NOT EDIT.

package DataSourceLib

func (_this *FieldModel) GetName() string {
	return _this.Name
}
func (_this *FieldModel) SetName(param string) {
	_this.Name = param
}
func (_this *FieldModel) GetType() int {
	return _this.Type
}
func (_this *FieldModel) SetType(param int) {
	_this.Type = param
}
func (_this *FieldModel) GetValue() interface{} {
	return _this.Value
}
func (_this *FieldModel) SetValue(param interface{}) {
	_this.Value = param
}
func (_this *FieldModel) GetExpression() string {
	return _this.Expression
}
func (_this *FieldModel) SetExpression(param string) {
	_this.Expression = param
}
func (_this *FieldModel) GetTableName() string {
	return _this.TableName
}
func (_this *FieldModel) SetTableName(param string) {
	_this.TableName = param
}
